export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS'
export const FETCH_RECIPES = 'FETCH_RECIPES'
export const ADD_INGREDIENT_TO_FILTER = 'ADD_INGREDIENT_TO_FILTER'
export const REMOVE_INGREDIENT_FROM_FILTER = 'REMOVE_INGREDIENT_FROM_FILTER'
